[env:uno]
platform = https://github.com/platformio/platform-atmelavr.git
board = uno
framework = arduino
build_unflags = -std=gnu++11 -std=gnu++14
build_flags = 
    -std=gnu++17
    -Werror
    -Wall
    -D SERIAL_ENABLED=true

lib_deps =
    BH1750
    adafruit/Adafruit BME280 Library

[platformio]
description = ESP32 based Weather station
